/**
 * Zuora REST APIs
 *  # Introduction  Introduction to Zuora Rest APIs. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: docs@zuora.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * GETProductRatePlanChargeFinanceInformationType
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-19T17:40:34.311Z")
public class GETProductRatePlanChargeFinanceInformationType   {
  @SerializedName("customField__c")
  private String customFieldC = null;

  @SerializedName("deferredRevenueAccountingCode")
  private String deferredRevenueAccountingCode = null;

  @SerializedName("deferredRevenueAccountingCodeType")
  private String deferredRevenueAccountingCodeType = null;

  @SerializedName("recognizedRevenueAccountingCode")
  private String recognizedRevenueAccountingCode = null;

  @SerializedName("recognizedRevenueAccountingCodeType")
  private String recognizedRevenueAccountingCodeType = null;

  public GETProductRatePlanChargeFinanceInformationType customFieldC(String customFieldC) {
    this.customFieldC = customFieldC;
    return this;
  }

   /**
   * Any custom fields defined for this object. 
   * @return customFieldC
  **/
  @ApiModelProperty(example = "null", value = "Any custom fields defined for this object. ")
  public String getCustomFieldC() {
    return customFieldC;
  }

  public void setCustomFieldC(String customFieldC) {
    this.customFieldC = customFieldC;
  }

  public GETProductRatePlanChargeFinanceInformationType deferredRevenueAccountingCode(String deferredRevenueAccountingCode) {
    this.deferredRevenueAccountingCode = deferredRevenueAccountingCode;
    return this;
  }

   /**
   * The accounting code for deferred revenue, such as Monthly Recurring Liability.  
   * @return deferredRevenueAccountingCode
  **/
  @ApiModelProperty(example = "null", value = "The accounting code for deferred revenue, such as Monthly Recurring Liability.  ")
  public String getDeferredRevenueAccountingCode() {
    return deferredRevenueAccountingCode;
  }

  public void setDeferredRevenueAccountingCode(String deferredRevenueAccountingCode) {
    this.deferredRevenueAccountingCode = deferredRevenueAccountingCode;
  }

  public GETProductRatePlanChargeFinanceInformationType deferredRevenueAccountingCodeType(String deferredRevenueAccountingCodeType) {
    this.deferredRevenueAccountingCodeType = deferredRevenueAccountingCodeType;
    return this;
  }

   /**
   * The type associated with the deferred revenue accounting code, such as Deferred Revenue.  
   * @return deferredRevenueAccountingCodeType
  **/
  @ApiModelProperty(example = "null", value = "The type associated with the deferred revenue accounting code, such as Deferred Revenue.  ")
  public String getDeferredRevenueAccountingCodeType() {
    return deferredRevenueAccountingCodeType;
  }

  public void setDeferredRevenueAccountingCodeType(String deferredRevenueAccountingCodeType) {
    this.deferredRevenueAccountingCodeType = deferredRevenueAccountingCodeType;
  }

  public GETProductRatePlanChargeFinanceInformationType recognizedRevenueAccountingCode(String recognizedRevenueAccountingCode) {
    this.recognizedRevenueAccountingCode = recognizedRevenueAccountingCode;
    return this;
  }

   /**
   * The accounting code for recognized revenue, such as Monthly Recurring Charges or Overage Charges.  
   * @return recognizedRevenueAccountingCode
  **/
  @ApiModelProperty(example = "null", value = "The accounting code for recognized revenue, such as Monthly Recurring Charges or Overage Charges.  ")
  public String getRecognizedRevenueAccountingCode() {
    return recognizedRevenueAccountingCode;
  }

  public void setRecognizedRevenueAccountingCode(String recognizedRevenueAccountingCode) {
    this.recognizedRevenueAccountingCode = recognizedRevenueAccountingCode;
  }

  public GETProductRatePlanChargeFinanceInformationType recognizedRevenueAccountingCodeType(String recognizedRevenueAccountingCodeType) {
    this.recognizedRevenueAccountingCodeType = recognizedRevenueAccountingCodeType;
    return this;
  }

   /**
   * The type associated with the recognized revenue accounting code, such as Sales Revenue or Sales Discount.  
   * @return recognizedRevenueAccountingCodeType
  **/
  @ApiModelProperty(example = "null", value = "The type associated with the recognized revenue accounting code, such as Sales Revenue or Sales Discount.  ")
  public String getRecognizedRevenueAccountingCodeType() {
    return recognizedRevenueAccountingCodeType;
  }

  public void setRecognizedRevenueAccountingCodeType(String recognizedRevenueAccountingCodeType) {
    this.recognizedRevenueAccountingCodeType = recognizedRevenueAccountingCodeType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETProductRatePlanChargeFinanceInformationType gETProductRatePlanChargeFinanceInformationType = (GETProductRatePlanChargeFinanceInformationType) o;
    return Objects.equals(this.customFieldC, gETProductRatePlanChargeFinanceInformationType.customFieldC) &&
        Objects.equals(this.deferredRevenueAccountingCode, gETProductRatePlanChargeFinanceInformationType.deferredRevenueAccountingCode) &&
        Objects.equals(this.deferredRevenueAccountingCodeType, gETProductRatePlanChargeFinanceInformationType.deferredRevenueAccountingCodeType) &&
        Objects.equals(this.recognizedRevenueAccountingCode, gETProductRatePlanChargeFinanceInformationType.recognizedRevenueAccountingCode) &&
        Objects.equals(this.recognizedRevenueAccountingCodeType, gETProductRatePlanChargeFinanceInformationType.recognizedRevenueAccountingCodeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customFieldC, deferredRevenueAccountingCode, deferredRevenueAccountingCodeType, recognizedRevenueAccountingCode, recognizedRevenueAccountingCodeType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETProductRatePlanChargeFinanceInformationType {\n");
    
    sb.append("    customFieldC: ").append(toIndentedString(customFieldC)).append("\n");
    sb.append("    deferredRevenueAccountingCode: ").append(toIndentedString(deferredRevenueAccountingCode)).append("\n");
    sb.append("    deferredRevenueAccountingCodeType: ").append(toIndentedString(deferredRevenueAccountingCodeType)).append("\n");
    sb.append("    recognizedRevenueAccountingCode: ").append(toIndentedString(recognizedRevenueAccountingCode)).append("\n");
    sb.append("    recognizedRevenueAccountingCodeType: ").append(toIndentedString(recognizedRevenueAccountingCodeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

