/**
 * Zuora REST APIs
 *  # Introduction  Introduction to Zuora Rest APIs. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: docs@zuora.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * POSTTransactionRSRevenueEventType
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-19T17:40:34.311Z")
public class POSTTransactionRSRevenueEventType   {
  @SerializedName("customField__c")
  private String customFieldC = null;

  @SerializedName("eventType")
  private String eventType = null;

  @SerializedName("eventTypeSystemId")
  private String eventTypeSystemId = null;

  @SerializedName("notes")
  private String notes = null;

  public POSTTransactionRSRevenueEventType customFieldC(String customFieldC) {
    this.customFieldC = customFieldC;
    return this;
  }

   /**
   * Any custom fields defined for this object. 
   * @return customFieldC
  **/
  @ApiModelProperty(example = "null", value = "Any custom fields defined for this object. ")
  public String getCustomFieldC() {
    return customFieldC;
  }

  public void setCustomFieldC(String customFieldC) {
    this.customFieldC = customFieldC;
  }

  public POSTTransactionRSRevenueEventType eventType(String eventType) {
    this.eventType = eventType;
    return this;
  }

   /**
   * Label of the revenue event type. Revenue event type labels can be duplicated. You can configure your revenue event type labels by navigating to **Settings > Z-Finance Settings > Configure Revenue Event Types** in the Zuora UI. The default revenue event types are: * Invoice Posted * Invoice Item Adjustment Created * Invoice Canceled * Invoice Item Adjustment Canceled * Revenue Distributed 
   * @return eventType
  **/
  @ApiModelProperty(example = "null", value = "Label of the revenue event type. Revenue event type labels can be duplicated. You can configure your revenue event type labels by navigating to **Settings > Z-Finance Settings > Configure Revenue Event Types** in the Zuora UI. The default revenue event types are: * Invoice Posted * Invoice Item Adjustment Created * Invoice Canceled * Invoice Item Adjustment Canceled * Revenue Distributed ")
  public String getEventType() {
    return eventType;
  }

  public void setEventType(String eventType) {
    this.eventType = eventType;
  }

  public POSTTransactionRSRevenueEventType eventTypeSystemId(String eventTypeSystemId) {
    this.eventTypeSystemId = eventTypeSystemId;
    return this;
  }

   /**
   * System ID of the revenue event type. Each eventType has a unique system ID. You can configure your revenue event type system IDs by navigating to **Settings > Z-Finance Settings > Configure Revenue Event Types** in the Zuora UI.  Required only if there is more than one revenue event type with the same label. 
   * @return eventTypeSystemId
  **/
  @ApiModelProperty(example = "null", value = "System ID of the revenue event type. Each eventType has a unique system ID. You can configure your revenue event type system IDs by navigating to **Settings > Z-Finance Settings > Configure Revenue Event Types** in the Zuora UI.  Required only if there is more than one revenue event type with the same label. ")
  public String getEventTypeSystemId() {
    return eventTypeSystemId;
  }

  public void setEventTypeSystemId(String eventTypeSystemId) {
    this.eventTypeSystemId = eventTypeSystemId;
  }

  public POSTTransactionRSRevenueEventType notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * Additional information about this record. 
   * @return notes
  **/
  @ApiModelProperty(example = "null", value = "Additional information about this record. ")
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    POSTTransactionRSRevenueEventType pOSTTransactionRSRevenueEventType = (POSTTransactionRSRevenueEventType) o;
    return Objects.equals(this.customFieldC, pOSTTransactionRSRevenueEventType.customFieldC) &&
        Objects.equals(this.eventType, pOSTTransactionRSRevenueEventType.eventType) &&
        Objects.equals(this.eventTypeSystemId, pOSTTransactionRSRevenueEventType.eventTypeSystemId) &&
        Objects.equals(this.notes, pOSTTransactionRSRevenueEventType.notes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customFieldC, eventType, eventTypeSystemId, notes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class POSTTransactionRSRevenueEventType {\n");
    
    sb.append("    customFieldC: ").append(toIndentedString(customFieldC)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    eventTypeSystemId: ").append(toIndentedString(eventTypeSystemId)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

